export const QUESTIONS_SEED = [
  {
    id: 1,
    text: 'Cuando despiertas, tu impulso natural es…',
    domain: 'identity',
    options: [
      { value: 1, label: 'Irme directo a la acción.' },
      { value: 2, label: 'Conectar con alguien / sentir el clima emocional.' },
      { value: 3, label: 'Revisar plan, prioridades y ruta.' },
      { value: 4, label: 'Tomar control del día y decidir.' },
      { value: 5, label: 'Imaginar posibilidades y crear algo nuevo.' },
      { value: 6, label: 'Ordenar, estructurar y hacer bien lo esencial.' },
      {
        value: 7,
        label: 'Observar señales, transformar el día “desde adentro”.',
      },
    ],
  },
  {
    id: 2,
    text: 'Lo que más te mueve por dentro es…',
    domain: 'identity',
    options: [
      { value: 1, label: 'La intensidad / reto.' },
      { value: 2, label: 'La unión / amor / pertenencia.' },
      { value: 3, label: 'Ganar ventaja con inteligencia.' },
      { value: 4, label: 'Poder construir y liderar.' },
      { value: 5, label: 'Visión, propósito, futuro.' },
      { value: 6, label: 'Estabilidad, precisión, progreso real.' },
      { value: 7, label: 'Misterio, cambio, evolución.' },
    ],
  },
  {
    id: 3,
    text: 'Cuando tienes una idea, tú…',
    domain: 'identity',
    options: [
      { value: 1, label: 'La pruebas ya.' },
      { value: 2, label: 'Se la compartes a alguien que confías.' },
      { value: 3, label: 'La conviertes en estrategia.' },
      { value: 4, label: 'La vuelves decisión.' },
      { value: 5, label: 'La expandes a 10 ideas más.' },
      { value: 6, label: 'La aterrizas con pasos y sistema.' },
      { value: 7, label: 'La sientes y la transformas hasta que “encaje”.' },
    ],
  },
  {
    id: 4,
    text: 'Tu mayor fortaleza suele ser…',
    domain: 'identity',
    options: [
      { value: 1, label: 'Valentía y empuje.' },
      { value: 2, label: 'Empatía y vínculo.' },
      { value: 3, label: 'Claridad mental y cálculo.' },
      { value: 4, label: 'Presencia y autoridad.' },
      { value: 5, label: 'Creatividad y visión.' },
      { value: 6, label: 'Disciplina y ejecución.' },
      { value: 7, label: 'Intuición y transmutación.' },
    ],
  },
  {
    id: 5,
    text: 'Tu defecto típico (cuando no te regulas) es…',
    domain: 'identity',
    options: [
      { value: 1, label: 'Impulsivo / me quemo rápido.' },
      { value: 2, label: 'Me pierdo por complacer.' },
      { value: 3, label: 'Frío / me aíslo.' },
      { value: 4, label: 'Controlador / duro.' },
      { value: 5, label: 'Disperso / idealista.' },
      { value: 6, label: 'Rígido / exigente.' },
      { value: 7, label: 'Intenso / enigmático.' },
    ],
  },
  {
    id: 6,
    text: 'Cuando la vida aprieta, tú sueles…',
    domain: 'identity',
    options: [
      { value: 1, label: 'Atacar el problema de frente.' },
      { value: 2, label: 'Buscar apoyo o reconciliación.' },
      { value: 3, label: 'Pensar más y sentir menos.' },
      { value: 4, label: 'Poner reglas y cortar.' },
      { value: 5, label: 'Escapar a la mente / soñar salida.' },
      { value: 6, label: 'Volverme más metódico y tenso.' },
      { value: 7, label: 'Volverme hermético y profundo.' },
    ],
  },
  {
    id: 7,
    text: 'Te sientes más vivo cuando…',
    domain: 'identity',
    options: [
      { value: 1, label: 'Hay adrenalina y avance.' },
      { value: 2, label: 'Hay amor y sinceridad.' },
      { value: 3, label: 'Hay reto intelectual.' },
      { value: 4, label: 'Hay impacto y liderazgo.' },
      { value: 5, label: 'Hay creación y libertad.' },
      { value: 6, label: 'Hay orden y mejora.' },
      { value: 7, label: 'Hay significado y transformación.' },
    ],
  },
  {
    id: 8,
    text: 'Tu manera de aprender es…',
    domain: 'identity',
    options: [
      { value: 1, label: 'Haciendo.' },
      { value: 2, label: 'Conversando y sintiendo.' },
      { value: 3, label: 'Investigando y comparando.' },
      { value: 4, label: 'Practicando con exigencia.' },
      { value: 5, label: 'Con imágenes, metáforas, ideas.' },
      { value: 6, label: 'Con método y repetición.' },
      { value: 7, label: 'Con experiencia interna / intuición.' },
    ],
  },
  {
    id: 9,
    text: 'Si te describen en una frase, sería…',
    domain: 'identity',
    options: [
      { value: 1, label: '“Va por todo.”' },
      { value: 2, label: '“Sostiene a los suyos.”' },
      { value: 3, label: '“Siempre ve el tablero.”' },
      { value: 4, label: '“Nació para mandar.”' },
      { value: 5, label: '“Piensa diferente.”' },
      { value: 6, label: '“Lo hace bien y a tiempo.”' },
      { value: 7, label: '“Tiene algo magnético.”' },
    ],
  },
  {
    id: 10,
    text: 'Tu “combustible” principal es…',
    domain: 'identity',
    options: [
      { value: 1, label: 'Desafío.' },
      { value: 2, label: 'Afecto.' },
      { value: 3, label: 'Información.' },
      { value: 4, label: 'Control/resultado.' },
      { value: 5, label: 'Inspiración.' },
      { value: 6, label: 'Proceso.' },
      { value: 7, label: 'Transformación.' },
    ],
  },
  {
    id: 11,
    text: 'En conversación, tú tiendes a…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Ir al grano y provocar acción.' },
      { value: 2, label: 'Escuchar y armonizar.' },
      { value: 3, label: 'Hacer preguntas y analizar.' },
      { value: 4, label: 'Marcar postura con firmeza.' },
      { value: 5, label: 'Contar ideas y posibilidades.' },
      { value: 6, label: 'Ordenar el tema y concretar.' },
      { value: 7, label: 'Leer entre líneas y profundizar.' },
    ],
  },
  {
    id: 12,
    text: 'Cuando te critican, tu primera reacción es…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Defenderme / competir.' },
      { value: 2, label: 'Me duele, quiero reparar.' },
      { value: 3, label: 'Me distancio y evalúo.' },
      { value: 4, label: 'Me pongo más firme.' },
      { value: 5, label: 'Lo relativizo / me voy a la visión.' },
      { value: 6, label: 'Me autoexijo más.' },
      { value: 7, label: 'Me cierro / me transformo en silencio.' },
    ],
  },
  {
    id: 13,
    text: 'Tu forma de decidir es…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Rápida.' },
      { value: 2, label: 'Considerando cómo afecta a todos.' },
      { value: 3, label: 'Comparando escenarios.' },
      { value: 4, label: 'Ejecutiva y definitiva.' },
      { value: 5, label: 'Intuitiva y creativa.' },
      { value: 6, label: 'Lógica, paso a paso.' },
      { value: 7, label: 'Energética: “se siente correcto o no”.' },
    ],
  },
  {
    id: 14,
    text: 'Cuando hay conflicto, tú…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Enfrentas.' },
      { value: 2, label: 'Buscas paz.' },
      { value: 3, label: 'Negocias con estrategia.' },
      { value: 4, label: 'Dominas o cortas.' },
      { value: 5, label: 'Lo reencuadras con visión.' },
      { value: 6, label: 'Pides reglas claras.' },
      { value: 7, label: 'Vas a la raíz emocional/espiritual.' },
    ],
  },
  {
    id: 15,
    text: 'Tu estilo de liderazgo es…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Por ejemplo y empuje.' },
      { value: 2, label: 'Por cuidado y cultura.' },
      { value: 3, label: 'Por dirección inteligente.' },
      { value: 4, label: 'Por autoridad y estándares.' },
      { value: 5, label: 'Por inspiración.' },
      { value: 6, label: 'Por procesos.' },
      { value: 7, label: 'Por propósito y transformación.' },
    ],
  },
  {
    id: 16,
    text: 'Cuando alguien te gusta, tú…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Avanzas directo.' },
      { value: 2, label: 'Creas vínculo y seguridad.' },
      { value: 3, label: 'Observas y calculas señales.' },
      { value: 4, label: 'Tomas iniciativa y “marcas territorio”.' },
      { value: 5, label: 'Fantaseas y conectas por mente/arte.' },
      { value: 6, label: 'Demuestras con hechos constantes.' },
      { value: 7, label: 'Conectas a nivel profundo/energético.' },
    ],
  },
  {
    id: 17,
    text: 'Cuando alguien te falla, tú…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Me enojo y sigo.' },
      { value: 2, label: 'Me afecta y quiero hablar.' },
      { value: 3, label: 'Tomo nota y ajusto límites.' },
      { value: 4, label: 'Corto o impongo consecuencias.' },
      { value: 5, label: 'Me decepciono y me voy a mi mundo.' },
      { value: 6, label: 'Pierdo confianza lentamente.' },
      { value: 7, label: 'Me cierro y transformo el vínculo.' },
    ],
  },
  {
    id: 18,
    text: 'Tu verdad sale más como…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Intensidad.' },
      { value: 2, label: 'Emoción.' },
      { value: 3, label: 'Argumento.' },
      { value: 4, label: 'Orden.' },
      { value: 5, label: 'Idea.' },
      { value: 6, label: 'Hecho.' },
      { value: 7, label: 'Intuición.' },
    ],
  },
  {
    id: 19,
    text: 'Tu debilidad social típica es…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Impaciencia.' },
      { value: 2, label: 'Apego.' },
      { value: 3, label: 'Distancia.' },
      { value: 4, label: 'Dominancia.' },
      { value: 5, label: 'Dispersión.' },
      { value: 6, label: 'Rigidez.' },
      { value: 7, label: 'Misterio/exceso de profundidad.' },
    ],
  },
  {
    id: 20,
    text: 'Tu manera de influir es…',
    domain: 'communication',
    options: [
      { value: 1, label: 'Por energía.' },
      { value: 2, label: 'Por cariño.' },
      { value: 3, label: 'Por lógica.' },
      { value: 4, label: 'Por autoridad.' },
      { value: 5, label: 'Por visión.' },
      { value: 6, label: 'Por consistencia.' },
      { value: 7, label: 'Por magnetismo.' },
    ],
  },
  {
    id: 21,
    text: 'En un equipo, tu rol natural es…',
    domain: 'work',
    options: [
      { value: 1, label: 'El que empuja.' },
      { value: 2, label: 'El que une.' },
      { value: 3, label: 'El que planifica.' },
      { value: 4, label: 'El que manda.' },
      { value: 5, label: 'El que crea.' },
      { value: 6, label: 'El que ejecuta perfecto.' },
      { value: 7, label: 'El que transforma el ambiente.' },
    ],
  },
  {
    id: 22,
    text: 'Te frustra más en un trabajo…',
    domain: 'work',
    options: [
      { value: 1, label: 'Lentitud.' },
      { value: 2, label: 'Frialdad humana.' },
      { value: 3, label: 'Caos sin estrategia.' },
      { value: 4, label: 'Falta de autoridad.' },
      { value: 5, label: 'Rutina sin creatividad.' },
      { value: 6, label: 'Desorden e improvisación.' },
      { value: 7, label: 'Falta de propósito.' },
    ],
  },
  {
    id: 23,
    text: 'Si te dan libertad total, tú…',
    domain: 'work',
    options: [
      { value: 1, label: 'Te lanzas a conquistar metas.' },
      { value: 2, label: 'Construyes comunidad/clientes fieles.' },
      { value: 3, label: 'Diseñas sistemas para ganar.' },
      { value: 4, label: 'Creas un imperio/operación.' },
      { value: 5, label: 'Innovas y exploras.' },
      { value: 6, label: 'Optimizarías procesos y calidad.' },
      { value: 7, label: 'Harías algo con significado profundo.' },
    ],
  },
  {
    id: 24,
    text: 'Tu mejor ambiente laboral es…',
    domain: 'work',
    options: [
      { value: 1, label: 'Reto + velocidad.' },
      { value: 2, label: 'Calidez + colaboración.' },
      { value: 3, label: 'Métricas + estrategia.' },
      { value: 4, label: 'Jerarquía + decisiones claras.' },
      { value: 5, label: 'Creativo + flexible.' },
      { value: 6, label: 'Ordenado + estable.' },
      { value: 7, label: 'Intenso + con propósito.' },
    ],
  },
  {
    id: 25,
    text: 'Cuando hay presión, tú rindes mejor si…',
    domain: 'work',
    options: [
      { value: 1, label: 'Hay competencia.' },
      { value: 2, label: 'Hay apoyo.' },
      { value: 3, label: 'Hay claridad de plan.' },
      { value: 4, label: 'Hay control y mando.' },
      { value: 5, label: 'Hay visión inspiradora.' },
      { value: 6, label: 'Hay checklist y método.' },
      { value: 7, label: 'Hay sentido y silencio.' },
    ],
  },
  {
    id: 26,
    text: 'Tu talento “premium” en negocio es…',
    domain: 'work',
    options: [
      { value: 1, label: 'Vender/atreverte/ejecutar.' },
      { value: 2, label: 'Retener, fidelizar, servicio.' },
      { value: 3, label: 'Estrategia, pricing, negociación.' },
      { value: 4, label: 'Liderar, cerrar, dirigir.' },
      { value: 5, label: 'Branding, ideas, contenido.' },
      { value: 6, label: 'Operaciones, producto, calidad.' },
      { value: 7, label: 'Cultura, transformación, insight.' },
    ],
  },
  {
    id: 27,
    text: 'Tú prefieres proyectos que…',
    domain: 'work',
    options: [
      { value: 1, label: 'Se ganan rápido.' },
      { value: 2, label: 'Ayudan gente.' },
      { value: 3, label: 'Se pueden medir.' },
      { value: 4, label: 'Escalan poder.' },
      { value: 5, label: 'Cambian el juego.' },
      { value: 6, label: 'Se construyen sólido.' },
      { value: 7, label: 'Evolucionan conciencia.' },
    ],
  },
  {
    id: 28,
    text: 'En un error, tú…',
    domain: 'work',
    options: [
      { value: 1, label: 'Corriges en caliente y sigues.' },
      { value: 2, label: 'Pides perdón y reparas.' },
      { value: 3, label: 'Analizas causa raíz.' },
      { value: 4, label: 'Pones consecuencias.' },
      { value: 5, label: 'Lo conviertes en aprendizaje creativo.' },
      { value: 6, label: 'Ajustas proceso para que no pase.' },
      { value: 7, label: 'Buscas el mensaje oculto.' },
    ],
  },
  {
    id: 29,
    text: 'Un jefe ideal para ti es…',
    domain: 'work',
    options: [
      { value: 1, label: 'Directo y retador.' },
      { value: 2, label: 'Humano y presente.' },
      { value: 3, label: 'Inteligente y justo.' },
      { value: 4, label: 'Fuerte y claro.' },
      { value: 5, label: 'Visionario y libre.' },
      { value: 6, label: 'Ordenado y consistente.' },
      { value: 7, label: 'Profundo e inspirador.' },
    ],
  },
  {
    id: 30,
    text: 'Tu camino ideal de carrera es…',
    domain: 'work',
    options: [
      { value: 1, label: 'Emprender/ventas/acción.' },
      { value: 2, label: 'Personas/bienestar/servicio.' },
      { value: 3, label: 'Consultoría/estrategia/finanzas.' },
      { value: 4, label: 'Dirección/management/negocio.' },
      { value: 5, label: 'Creativo/innovación/medios.' },
      { value: 6, label: 'Ingeniería/ops/producto/sistemas.' },
      { value: 7, label: 'Psicología/coaching/arte profundo/transformación.' },
    ],
  },
  {
    id: 31,
    text: 'En un grupo, tú eres…',
    domain: 'social',
    options: [
      { value: 1, label: 'El que prende la energía.' },
      { value: 2, label: 'El que cuida a todos.' },
      { value: 3, label: 'El que observa el tablero social.' },
      { value: 4, label: 'El que marca el ritmo/reglas.' },
      { value: 5, label: 'El que trae ideas y humor raro.' },
      { value: 6, label: 'El que organiza y resuelve.' },
      { value: 7, label: 'El que conecta profundo con pocos.' },
    ],
  },
  {
    id: 32,
    text: 'Tu forma de hacer amigos es…',
    domain: 'social',
    options: [
      { value: 1, label: 'Por aventura.' },
      { value: 2, label: 'Por confianza.' },
      { value: 3, label: 'Por intereses mentales.' },
      { value: 4, label: 'Por respeto.' },
      { value: 5, label: 'Por creatividad.' },
      { value: 6, label: 'Por constancia.' },
      { value: 7, label: 'Por intimidad emocional.' },
    ],
  },
  {
    id: 33,
    text: 'Te drena socialmente cuando…',
    domain: 'social',
    options: [
      { value: 1, label: 'Todo es lento.' },
      { value: 2, label: 'Hay frialdad.' },
      { value: 3, label: 'Hay superficialidad.' },
      { value: 4, label: 'Nadie decide.' },
      { value: 5, label: 'Hay rutina.' },
      { value: 6, label: 'Hay caos.' },
      { value: 7, label: 'Hay falsedad.' },
    ],
  },
  {
    id: 34,
    text: 'En fiestas, tú…',
    domain: 'social',
    options: [
      { value: 1, label: 'Te mueves y activas.' },
      { value: 2, label: 'Conectas 1 a 1 con cariño.' },
      { value: 3, label: 'Hablas con pocos pero bien.' },
      { value: 4, label: 'Dominas el espacio o te vas.' },
      { value: 5, label: 'Te vuelves creativo/performer.' },
      { value: 6, label: 'Aseguras que todo funcione.' },
      { value: 7, label: 'Te vas a conversaciones profundas.' },
    ],
  },
  {
    id: 35,
    text: 'Tu límite social sano es…',
    domain: 'social',
    options: [
      { value: 1, label: 'No aguanto drama.' },
      { value: 2, label: 'No aguanto falta de afecto.' },
      { value: 3, label: 'No aguanto irracionalidad.' },
      { value: 4, label: 'No aguanto falta de respeto.' },
      { value: 5, label: 'No aguanto encierro creativo.' },
      { value: 6, label: 'No aguanto improvisación eterna.' },
      { value: 7, label: 'No aguanto mentira.' },
    ],
  },
  {
    id: 36,
    text: 'Para ti el dinero es…',
    domain: 'money',
    options: [
      { value: 1, label: 'Libertad para moverte.' },
      { value: 2, label: 'Seguridad para los tuyos.' },
      { value: 3, label: 'Herramienta para estrategia.' },
      { value: 4, label: 'Poder para construir.' },
      { value: 5, label: 'Combustible para crear.' },
      { value: 6, label: 'Estabilidad y orden.' },
      { value: 7, label: 'Energía que amplifica propósito.' },
    ],
  },
  {
    id: 37,
    text: 'Tu estilo de gasto es…',
    domain: 'money',
    options: [
      { value: 1, label: 'Rápido: experiencias/acción.' },
      { value: 2, label: 'En regalos/afecto/hogar.' },
      { value: 3, label: 'En herramientas/educación.' },
      { value: 4, label: 'En status/crecimiento.' },
      { value: 5, label: 'En arte/ideas/viajes.' },
      { value: 6, label: 'En calidad/ahorro.' },
      { value: 7, label: 'En experiencias transformadoras.' },
    ],
  },
  {
    id: 38,
    text: 'Tu riesgo financiero típico es…',
    domain: 'money',
    options: [
      { value: 1, label: 'Impulsividad.' },
      { value: 2, label: 'Dar de más.' },
      { value: 3, label: 'Sobre-analizar y perder timing.' },
      { value: 4, label: 'Exceso de control/apuesta grande.' },
      { value: 5, label: 'Dispersión.' },
      { value: 6, label: 'Miedo a mover capital.' },
      { value: 7, label: 'Misterio: decisiones por intuición sin datos.' },
    ],
  },
  {
    id: 39,
    text: 'Tu mejor estrategia de dinero sería…',
    domain: 'money',
    options: [
      { value: 1, label: 'Metas cortas + acción constante.' },
      { value: 2, label: 'Presupuesto emocional + ahorro para estabilidad.' },
      { value: 3, label: 'Portafolio + métricas + optimización.' },
      { value: 4, label: 'Cashflow + liderazgo + escala.' },
      { value: 5, label: 'Diversificación creativa + marca personal.' },
      { value: 6, label: 'Sistemas + automatización + fondo.' },
      { value: 7, label: 'Propósito + intuición con reglas.' },
    ],
  },
  {
    id: 40,
    text: 'Si tuvieras 10x ingresos, tú…',
    domain: 'money',
    options: [
      { value: 1, label: 'Irías por metas más grandes ya.' },
      { value: 2, label: 'Aseguras familia y ayudas.' },
      { value: 3, label: 'Inviertes y optimizas.' },
      { value: 4, label: 'Compras activos y poder.' },
      { value: 5, label: 'Creas proyectos épicos.' },
      { value: 6, label: 'Construyes patrimonio sólido.' },
      { value: 7, label: 'Te vuelves mentor/creador profundo.' },
    ],
  },
  {
    id: 41,
    text: 'Bajo estrés, tu impulso oscuro es…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Exploto / me vuelvo agresivo.' },
      { value: 2, label: 'Me apego / necesito validación.' },
      { value: 3, label: 'Me vuelvo frío y calculador.' },
      { value: 4, label: 'Me vuelvo dominante e inflexible.' },
      { value: 5, label: 'Me pierdo en fantasía y evito.' },
      { value: 6, label: 'Me vuelvo perfeccionista y duro.' },
      { value: 7, label: 'Me cierro, sospecho, me vuelvo intenso.' },
    ],
  },
  {
    id: 42,
    text: 'Cuando te sientes inseguro, tú…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Atacas primero.' },
      { value: 2, label: 'Pides amor/atención.' },
      { value: 3, label: 'Controlas con información.' },
      { value: 4, label: 'Controlas con autoridad.' },
      { value: 5, label: 'Escapas mentalmente.' },
      { value: 6, label: 'Te rigidizas con reglas.' },
      { value: 7, label: 'Te vuelves enigmático y distante.' },
    ],
  },
  {
    id: 43,
    text: 'Tu reacción tóxica más probable es…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Impulsar/pelear.' },
      { value: 2, label: 'Victimizarme/rogar.' },
      { value: 3, label: 'Manipular con lógica.' },
      { value: 4, label: 'Intimidar.' },
      { value: 5, label: 'Prometer sin sostener.' },
      { value: 6, label: 'Criticar y exigir.' },
      { value: 7, label: 'Castigar con silencio.' },
    ],
  },
  {
    id: 44,
    text: 'En un conflicto de pareja bajo estrés, tú…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Entras fuerte.' },
      { value: 2, label: 'Suplicas conexión.' },
      { value: 3, label: 'Discutes con argumentos.' },
      { value: 4, label: 'Cortas o impones.' },
      { value: 5, label: 'Te vas emocionalmente.' },
      { value: 6, label: 'Sacas lista de “fallas”.' },
      { value: 7, label: 'Te vuelves inaccesible.' },
    ],
  },
  {
    id: 45,
    text: 'Cuando sientes que pierdes control…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Me acelero.' },
      { value: 2, label: 'Me aferro.' },
      { value: 3, label: 'Me desconecto del corazón.' },
      { value: 4, label: 'Aprieto más.' },
      { value: 5, label: 'Me disperso.' },
      { value: 6, label: 'Me obsesiono con detalles.' },
      { value: 7, label: 'Me vuelvo oscuro/obsesivo.' },
    ],
  },
  {
    id: 46,
    text: 'Tu sombra se activa más cuando…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Te frenan.' },
      { value: 2, label: 'Te ignoran.' },
      { value: 3, label: 'Te subestiman.' },
      { value: 4, label: 'Te faltan al respeto.' },
      { value: 5, label: 'Te encierran.' },
      { value: 6, label: 'Te desordenan.' },
      { value: 7, label: 'Te mienten.' },
    ],
  },
  {
    id: 47,
    text: 'Cuando estás herido, tú…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Hago daño de regreso.' },
      { value: 2, label: 'Me rompo y busco rescate.' },
      { value: 3, label: 'Me vuelvo hielo.' },
      { value: 4, label: 'Me vuelvo juez.' },
      { value: 5, label: 'Desaparezco.' },
      { value: 6, label: 'Me vuelvo crítico.' },
      { value: 7, label: 'Me vuelvo sombra silenciosa.' },
    ],
  },
  {
    id: 48,
    text: 'Lo que más te cuesta admitir es…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Miedo a perder.' },
      { value: 2, label: 'Miedo a estar solo.' },
      { value: 3, label: 'Miedo a sentir.' },
      { value: 4, label: 'Miedo a no ser suficiente.' },
      { value: 5, label: 'Miedo a no lograr mi visión.' },
      { value: 6, label: 'Miedo al caos.' },
      { value: 7, label: 'Miedo a confiar.' },
    ],
  },
  {
    id: 49,
    text: 'Tu señal temprana de sombra es…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Impaciencia física.' },
      { value: 2, label: 'Ansiedad por atención.' },
      { value: 3, label: 'Rumiar mental.' },
      { value: 4, label: 'Tensión de control.' },
      { value: 5, label: 'Procrastinación creativa.' },
      { value: 6, label: 'Rigidez corporal/orden excesivo.' },
      { value: 7, label: 'Silencio pesado.' },
    ],
  },
  {
    id: 50,
    text: 'Tu antídoto más efectivo suele ser…',
    domain: 'shadow',
    options: [
      { value: 1, label: 'Movimiento + objetivo claro.' },
      { value: 2, label: 'Contacto humano + ternura.' },
      { value: 3, label: 'Escribir plan simple + acción mínima.' },
      { value: 4, label: 'Delegar + humildad.' },
      { value: 5, label: 'Limitar opciones + rutina creativa.' },
      { value: 6, label: 'Soltar “perfección” + priorizar 1 cosa.' },
      { value: 7, label: 'Respirar + verdad + significado.' },
    ],
  },
];
